apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: flux-operator
  annotations:
    helmcharts.cattle.io/managed-by: helm-controller
  finalizers:
  - wrangler.cattle.io/on-helm-chart-remove
  generation: 1
  namespace: default
spec:
  targetNamespace: flux-system
  chart: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
  version: 0.41.0
  valuesContent: |-
    web:
      enabled: true
      ingress:
        className: traefik
        enabled: true
        hosts:
          - host: <HOSTNAME> 
            paths:
              - path: /
                pathType: Prefix
          
---
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "1h"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  distribution:
    version: "2.x"
    registry: "ghcr.io/fluxcd"
    artifact: "oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
    - image-reflector-controller
    - image-automation-controller
  cluster:
    type: kubernetes
    size: small
    multitenant: false
    networkPolicy: true
    domain: "cluster.local"
  kustomize:
    patches:
      - target:
          kind: Deployment
        patch: |
          - op: replace
            path: /spec/template/spec/nodeSelector
            value:
              kubernetes.io/os: linux
          - op: add
            path: /spec/template/spec/tolerations
            value:
              - key: "CriticalAddonsOnly"
                operator: "Exists"          
  sync:
    kind: GitRepository
    url: "github.com/yoyozbi-homelab/k8s-config"
    ref: "main"
    path: "clusters/ocr1"
    pullSecret: "ghcr-auth"
---
